# This workflow will push the iD source strings to transifex
# - requires TX_TOKEN secret to be set on GitHub
# - you can generate a token at https://www.transifex.com/user/settings/api/
# - job should fail silently if no token provided

name: transifex

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  transifex:
    runs-on: ubuntu-latest
    environment: workflows

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
        source ~/.bashrc
    - name: Create .transifexrc
      uses: DamianReeves/write-file-action@e19fd875ed54f16fc583a3486e62547ce4a5dde8
      with:
        path: .transifexrc
        write-mode: overwrite
        contents: |
          [https://www.transifex.com]
          token = ${{secrets.TX_TOKEN}}
    - name: Push source strings to Transifex
      run: tx push --source --no-interactive
